global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Your C++ application metrics
  - job_name: "cpp-service"
    static_configs:
      - targets: ["cpp-service:8080"]
    scrape_interval: 5s
    metrics_path: /metrics

  # cAdvisor for container metrics
  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]
    scrape_interval: 5s
    metrics_path: /metrics

  # Prometheus self-monitoring
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
